// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: poolmanager.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNKNOWN Status = 0
	Status_CREATE         Status = 1
	Status_UPDATE         Status = 2
	Status_DELETE         Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "CREATE",
		2: "UPDATE",
		3: "DELETE",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"CREATE":         1,
		"UPDATE":         2,
		"DELETE":         3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_poolmanager_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_poolmanager_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_poolmanager_proto_rawDescGZIP(), []int{0}
}

type Type int32

const (
	Type_TYPE_UNKNOWN Type = 0
	Type_SERVERPOOL   Type = 1
	Type_SERVER       Type = 2
	Type_CONFIG       Type = 3
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "SERVERPOOL",
		2: "SERVER",
		3: "CONFIG",
	}
	Type_value = map[string]int32{
		"TYPE_UNKNOWN": 0,
		"SERVERPOOL":   1,
		"SERVER":       2,
		"CONFIG":       3,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_poolmanager_proto_enumTypes[1].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_poolmanager_proto_enumTypes[1]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_poolmanager_proto_rawDescGZIP(), []int{1}
}

type RessourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Data          map[string]string      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RessourceRequest) Reset() {
	*x = RessourceRequest{}
	mi := &file_poolmanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RessourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RessourceRequest) ProtoMessage() {}

func (x *RessourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poolmanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RessourceRequest.ProtoReflect.Descriptor instead.
func (*RessourceRequest) Descriptor() ([]byte, []int) {
	return file_poolmanager_proto_rawDescGZIP(), []int{0}
}

func (x *RessourceRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RessourceRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_poolmanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poolmanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_poolmanager_proto_rawDescGZIP(), []int{1}
}

func (x *UserRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type StreamRessourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=poolmanager.Status" json:"status,omitempty"`
	Type          Type                   `protobuf:"varint,3,opt,name=type,proto3,enum=poolmanager.Type" json:"type,omitempty"`
	Data          map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRessourceResponse) Reset() {
	*x = StreamRessourceResponse{}
	mi := &file_poolmanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRessourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRessourceResponse) ProtoMessage() {}

func (x *StreamRessourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poolmanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRessourceResponse.ProtoReflect.Descriptor instead.
func (*StreamRessourceResponse) Descriptor() ([]byte, []int) {
	return file_poolmanager_proto_rawDescGZIP(), []int{2}
}

func (x *StreamRessourceResponse) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *StreamRessourceResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *StreamRessourceResponse) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNKNOWN
}

func (x *StreamRessourceResponse) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_poolmanager_proto protoreflect.FileDescriptor

const file_poolmanager_proto_rawDesc = "" +
	"\n" +
	"\x11poolmanager.proto\x12\vpoolmanager\x1a\x1bgoogle/protobuf/empty.proto\"\x9c\x01\n" +
	"\x10RessourceRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12;\n" +
	"\x04data\x18\x02 \x03(\v2'.poolmanager.RessourceRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\vUserRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\"\xfe\x01\n" +
	"\x17StreamRessourceResponse\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.poolmanager.StatusR\x06status\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.poolmanager.TypeR\x04type\x12B\n" +
	"\x04data\x18\x04 \x03(\v2..poolmanager.StreamRessourceResponse.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*@\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03*@\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"SERVERPOOL\x10\x01\x12\n" +
	"\n" +
	"\x06SERVER\x10\x02\x12\n" +
	"\n" +
	"\x06CONFIG\x10\x032\x8a\x02\n" +
	"\vPoolManager\x12G\n" +
	"\x0eSendRessources\x12\x1d.poolmanager.RessourceRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\x13GetStreamRessources\x12\x16.google.protobuf.Empty\x1a$.poolmanager.StreamRessourceResponse0\x01\x12[\n" +
	"\x17GetStreamRessourcesUser\x12\x18.poolmanager.UserRequest\x1a$.poolmanager.StreamRessourceResponse0\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_poolmanager_proto_rawDescOnce sync.Once
	file_poolmanager_proto_rawDescData []byte
)

func file_poolmanager_proto_rawDescGZIP() []byte {
	file_poolmanager_proto_rawDescOnce.Do(func() {
		file_poolmanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poolmanager_proto_rawDesc), len(file_poolmanager_proto_rawDesc)))
	})
	return file_poolmanager_proto_rawDescData
}

var file_poolmanager_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_poolmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_poolmanager_proto_goTypes = []any{
	(Status)(0),                     // 0: poolmanager.Status
	(Type)(0),                       // 1: poolmanager.Type
	(*RessourceRequest)(nil),        // 2: poolmanager.RessourceRequest
	(*UserRequest)(nil),             // 3: poolmanager.UserRequest
	(*StreamRessourceResponse)(nil), // 4: poolmanager.StreamRessourceResponse
	nil,                             // 5: poolmanager.RessourceRequest.DataEntry
	nil,                             // 6: poolmanager.StreamRessourceResponse.DataEntry
	(*emptypb.Empty)(nil),           // 7: google.protobuf.Empty
}
var file_poolmanager_proto_depIdxs = []int32{
	5, // 0: poolmanager.RessourceRequest.data:type_name -> poolmanager.RessourceRequest.DataEntry
	0, // 1: poolmanager.StreamRessourceResponse.status:type_name -> poolmanager.Status
	1, // 2: poolmanager.StreamRessourceResponse.type:type_name -> poolmanager.Type
	6, // 3: poolmanager.StreamRessourceResponse.data:type_name -> poolmanager.StreamRessourceResponse.DataEntry
	2, // 4: poolmanager.PoolManager.SendRessources:input_type -> poolmanager.RessourceRequest
	7, // 5: poolmanager.PoolManager.GetStreamRessources:input_type -> google.protobuf.Empty
	3, // 6: poolmanager.PoolManager.GetStreamRessourcesUser:input_type -> poolmanager.UserRequest
	7, // 7: poolmanager.PoolManager.SendRessources:output_type -> google.protobuf.Empty
	4, // 8: poolmanager.PoolManager.GetStreamRessources:output_type -> poolmanager.StreamRessourceResponse
	4, // 9: poolmanager.PoolManager.GetStreamRessourcesUser:output_type -> poolmanager.StreamRessourceResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_poolmanager_proto_init() }
func file_poolmanager_proto_init() {
	if File_poolmanager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poolmanager_proto_rawDesc), len(file_poolmanager_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poolmanager_proto_goTypes,
		DependencyIndexes: file_poolmanager_proto_depIdxs,
		EnumInfos:         file_poolmanager_proto_enumTypes,
		MessageInfos:      file_poolmanager_proto_msgTypes,
	}.Build()
	File_poolmanager_proto = out.File
	file_poolmanager_proto_goTypes = nil
	file_poolmanager_proto_depIdxs = nil
}
