// source: poolmanager.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.poolmanager.Flavor', null, global);
goog.exportSymbol('proto.poolmanager.Image', null, global);
goog.exportSymbol('proto.poolmanager.Network', null, global);
goog.exportSymbol('proto.poolmanager.RessourceRequest', null, global);
goog.exportSymbol('proto.poolmanager.Status', null, global);
goog.exportSymbol('proto.poolmanager.StreamRessourceResponse', null, global);
goog.exportSymbol('proto.poolmanager.Type', null, global);
goog.exportSymbol('proto.poolmanager.UserRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.poolmanager.RessourceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.poolmanager.RessourceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.poolmanager.RessourceRequest.displayName = 'proto.poolmanager.RessourceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.poolmanager.UserRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.poolmanager.UserRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.poolmanager.UserRequest.displayName = 'proto.poolmanager.UserRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.poolmanager.StreamRessourceResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.poolmanager.StreamRessourceResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.poolmanager.StreamRessourceResponse.displayName = 'proto.poolmanager.StreamRessourceResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.poolmanager.Image = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.poolmanager.Image, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.poolmanager.Image.displayName = 'proto.poolmanager.Image';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.poolmanager.Flavor = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.poolmanager.Flavor, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.poolmanager.Flavor.displayName = 'proto.poolmanager.Flavor';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.poolmanager.Network = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.poolmanager.Network, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.poolmanager.Network.displayName = 'proto.poolmanager.Network';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.poolmanager.RessourceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.poolmanager.RessourceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.poolmanager.RessourceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.poolmanager.RessourceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
user: jspb.Message.getFieldWithDefault(msg, 1, ""),
dataMap: (f = msg.getDataMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.poolmanager.RessourceRequest}
 */
proto.poolmanager.RessourceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.poolmanager.RessourceRequest;
  return proto.poolmanager.RessourceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.poolmanager.RessourceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.poolmanager.RessourceRequest}
 */
proto.poolmanager.RessourceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUser(value);
      break;
    case 2:
      var value = msg.getDataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.poolmanager.RessourceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.poolmanager.RessourceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.poolmanager.RessourceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.poolmanager.RessourceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUser();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string user = 1;
 * @return {string}
 */
proto.poolmanager.RessourceRequest.prototype.getUser = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.RessourceRequest} returns this
 */
proto.poolmanager.RessourceRequest.prototype.setUser = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * map<string, string> data = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.poolmanager.RessourceRequest.prototype.getDataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.poolmanager.RessourceRequest} returns this
 */
proto.poolmanager.RessourceRequest.prototype.clearDataMap = function() {
  this.getDataMap().clear();
  return this;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.poolmanager.UserRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.poolmanager.UserRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.poolmanager.UserRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.poolmanager.UserRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
user: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.poolmanager.UserRequest}
 */
proto.poolmanager.UserRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.poolmanager.UserRequest;
  return proto.poolmanager.UserRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.poolmanager.UserRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.poolmanager.UserRequest}
 */
proto.poolmanager.UserRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUser(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.poolmanager.UserRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.poolmanager.UserRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.poolmanager.UserRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.poolmanager.UserRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUser();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string user = 1;
 * @return {string}
 */
proto.poolmanager.UserRequest.prototype.getUser = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.UserRequest} returns this
 */
proto.poolmanager.UserRequest.prototype.setUser = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.poolmanager.StreamRessourceResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.poolmanager.StreamRessourceResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.poolmanager.StreamRessourceResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.poolmanager.StreamRessourceResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
user: jspb.Message.getFieldWithDefault(msg, 1, ""),
status: jspb.Message.getFieldWithDefault(msg, 2, 0),
type: jspb.Message.getFieldWithDefault(msg, 3, 0),
dataMap: (f = msg.getDataMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.poolmanager.StreamRessourceResponse}
 */
proto.poolmanager.StreamRessourceResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.poolmanager.StreamRessourceResponse;
  return proto.poolmanager.StreamRessourceResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.poolmanager.StreamRessourceResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.poolmanager.StreamRessourceResponse}
 */
proto.poolmanager.StreamRessourceResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUser(value);
      break;
    case 2:
      var value = /** @type {!proto.poolmanager.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 3:
      var value = /** @type {!proto.poolmanager.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 4:
      var value = msg.getDataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.poolmanager.StreamRessourceResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.poolmanager.StreamRessourceResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.poolmanager.StreamRessourceResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.poolmanager.StreamRessourceResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUser();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getDataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string user = 1;
 * @return {string}
 */
proto.poolmanager.StreamRessourceResponse.prototype.getUser = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.StreamRessourceResponse} returns this
 */
proto.poolmanager.StreamRessourceResponse.prototype.setUser = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Status status = 2;
 * @return {!proto.poolmanager.Status}
 */
proto.poolmanager.StreamRessourceResponse.prototype.getStatus = function() {
  return /** @type {!proto.poolmanager.Status} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.poolmanager.Status} value
 * @return {!proto.poolmanager.StreamRessourceResponse} returns this
 */
proto.poolmanager.StreamRessourceResponse.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional Type type = 3;
 * @return {!proto.poolmanager.Type}
 */
proto.poolmanager.StreamRessourceResponse.prototype.getType = function() {
  return /** @type {!proto.poolmanager.Type} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.poolmanager.Type} value
 * @return {!proto.poolmanager.StreamRessourceResponse} returns this
 */
proto.poolmanager.StreamRessourceResponse.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * map<string, string> data = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.poolmanager.StreamRessourceResponse.prototype.getDataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.poolmanager.StreamRessourceResponse} returns this
 */
proto.poolmanager.StreamRessourceResponse.prototype.clearDataMap = function() {
  this.getDataMap().clear();
  return this;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.poolmanager.Image.prototype.toObject = function(opt_includeInstance) {
  return proto.poolmanager.Image.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.poolmanager.Image} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.poolmanager.Image.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, ""),
name: jspb.Message.getFieldWithDefault(msg, 2, ""),
status: jspb.Message.getFieldWithDefault(msg, 3, ""),
tags: jspb.Message.getFieldWithDefault(msg, 4, ""),
containerFormat: jspb.Message.getFieldWithDefault(msg, 5, ""),
diskFormat: jspb.Message.getFieldWithDefault(msg, 6, ""),
minDiskGigabytes: jspb.Message.getFieldWithDefault(msg, 7, 0),
minRamMegabytes: jspb.Message.getFieldWithDefault(msg, 8, 0),
owner: jspb.Message.getFieldWithDefault(msg, 9, ""),
pb_protected: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
visibility: jspb.Message.getFieldWithDefault(msg, 11, ""),
hidden: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
checksum: jspb.Message.getFieldWithDefault(msg, 13, ""),
sizeBytes: jspb.Message.getFieldWithDefault(msg, 14, 0),
createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
file: jspb.Message.getFieldWithDefault(msg, 17, ""),
schema: jspb.Message.getFieldWithDefault(msg, 18, ""),
virtualSize: jspb.Message.getFieldWithDefault(msg, 19, 0),
importMethods: jspb.Message.getFieldWithDefault(msg, 20, ""),
storeIds: jspb.Message.getFieldWithDefault(msg, 21, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.poolmanager.Image}
 */
proto.poolmanager.Image.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.poolmanager.Image;
  return proto.poolmanager.Image.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.poolmanager.Image} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.poolmanager.Image}
 */
proto.poolmanager.Image.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTags(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setContainerFormat(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDiskFormat(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMinDiskGigabytes(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMinRamMegabytes(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwner(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setProtected(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setVisibility(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHidden(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setChecksum(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSizeBytes(value);
      break;
    case 15:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 16:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setFile(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setSchema(value);
      break;
    case 19:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setVirtualSize(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setImportMethods(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setStoreIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.poolmanager.Image.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.poolmanager.Image.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.poolmanager.Image} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.poolmanager.Image.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTags();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getContainerFormat();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDiskFormat();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getMinDiskGigabytes();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getMinRamMegabytes();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getOwner();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getProtected();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getVisibility();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getHidden();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
  f = message.getChecksum();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getSizeBytes();
  if (f !== 0) {
    writer.writeInt64(
      14,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getFile();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getSchema();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getVirtualSize();
  if (f !== 0) {
    writer.writeInt64(
      19,
      f
    );
  }
  f = message.getImportMethods();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getStoreIds();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.poolmanager.Image.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.poolmanager.Image.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string status = 3;
 * @return {string}
 */
proto.poolmanager.Image.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string tags = 4;
 * @return {string}
 */
proto.poolmanager.Image.prototype.getTags = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setTags = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string container_format = 5;
 * @return {string}
 */
proto.poolmanager.Image.prototype.getContainerFormat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setContainerFormat = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string disk_format = 6;
 * @return {string}
 */
proto.poolmanager.Image.prototype.getDiskFormat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setDiskFormat = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int32 min_disk_gigabytes = 7;
 * @return {number}
 */
proto.poolmanager.Image.prototype.getMinDiskGigabytes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setMinDiskGigabytes = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 min_ram_megabytes = 8;
 * @return {number}
 */
proto.poolmanager.Image.prototype.getMinRamMegabytes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setMinRamMegabytes = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional string owner = 9;
 * @return {string}
 */
proto.poolmanager.Image.prototype.getOwner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setOwner = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional bool protected = 10;
 * @return {boolean}
 */
proto.poolmanager.Image.prototype.getProtected = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setProtected = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional string visibility = 11;
 * @return {string}
 */
proto.poolmanager.Image.prototype.getVisibility = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setVisibility = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional bool hidden = 12;
 * @return {boolean}
 */
proto.poolmanager.Image.prototype.getHidden = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setHidden = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};


/**
 * optional string checksum = 13;
 * @return {string}
 */
proto.poolmanager.Image.prototype.getChecksum = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setChecksum = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional int64 size_bytes = 14;
 * @return {number}
 */
proto.poolmanager.Image.prototype.getSizeBytes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setSizeBytes = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 15;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.poolmanager.Image.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 15));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.poolmanager.Image} returns this
*/
proto.poolmanager.Image.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.poolmanager.Image.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 16;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.poolmanager.Image.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 16));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.poolmanager.Image} returns this
*/
proto.poolmanager.Image.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.poolmanager.Image.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional string file = 17;
 * @return {string}
 */
proto.poolmanager.Image.prototype.getFile = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setFile = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional string schema = 18;
 * @return {string}
 */
proto.poolmanager.Image.prototype.getSchema = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setSchema = function(value) {
  return jspb.Message.setProto3StringField(this, 18, value);
};


/**
 * optional int64 virtual_size = 19;
 * @return {number}
 */
proto.poolmanager.Image.prototype.getVirtualSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/**
 * @param {number} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setVirtualSize = function(value) {
  return jspb.Message.setProto3IntField(this, 19, value);
};


/**
 * optional string import_methods = 20;
 * @return {string}
 */
proto.poolmanager.Image.prototype.getImportMethods = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setImportMethods = function(value) {
  return jspb.Message.setProto3StringField(this, 20, value);
};


/**
 * optional string store_ids = 21;
 * @return {string}
 */
proto.poolmanager.Image.prototype.getStoreIds = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Image} returns this
 */
proto.poolmanager.Image.prototype.setStoreIds = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.poolmanager.Flavor.prototype.toObject = function(opt_includeInstance) {
  return proto.poolmanager.Flavor.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.poolmanager.Flavor} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.poolmanager.Flavor.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, ""),
name: jspb.Message.getFieldWithDefault(msg, 2, ""),
disk: jspb.Message.getFieldWithDefault(msg, 3, 0),
ram: jspb.Message.getFieldWithDefault(msg, 4, 0),
vcpus: jspb.Message.getFieldWithDefault(msg, 5, 0),
rxtxFactor: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
swap: jspb.Message.getFieldWithDefault(msg, 7, 0),
ephemeral: jspb.Message.getFieldWithDefault(msg, 8, 0),
isPublic: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
description: jspb.Message.getFieldWithDefault(msg, 10, ""),
extraSpecs: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.poolmanager.Flavor}
 */
proto.poolmanager.Flavor.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.poolmanager.Flavor;
  return proto.poolmanager.Flavor.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.poolmanager.Flavor} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.poolmanager.Flavor}
 */
proto.poolmanager.Flavor.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDisk(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRam(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setVcpus(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setRxtxFactor(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSwap(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setEphemeral(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsPublic(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setExtraSpecs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.poolmanager.Flavor.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.poolmanager.Flavor.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.poolmanager.Flavor} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.poolmanager.Flavor.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDisk();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getRam();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getVcpus();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getRxtxFactor();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getSwap();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getEphemeral();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getIsPublic();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getExtraSpecs();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.poolmanager.Flavor.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Flavor} returns this
 */
proto.poolmanager.Flavor.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.poolmanager.Flavor.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Flavor} returns this
 */
proto.poolmanager.Flavor.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 disk = 3;
 * @return {number}
 */
proto.poolmanager.Flavor.prototype.getDisk = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.poolmanager.Flavor} returns this
 */
proto.poolmanager.Flavor.prototype.setDisk = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 ram = 4;
 * @return {number}
 */
proto.poolmanager.Flavor.prototype.getRam = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.poolmanager.Flavor} returns this
 */
proto.poolmanager.Flavor.prototype.setRam = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 vcpus = 5;
 * @return {number}
 */
proto.poolmanager.Flavor.prototype.getVcpus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.poolmanager.Flavor} returns this
 */
proto.poolmanager.Flavor.prototype.setVcpus = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional double rxtx_factor = 6;
 * @return {number}
 */
proto.poolmanager.Flavor.prototype.getRxtxFactor = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.poolmanager.Flavor} returns this
 */
proto.poolmanager.Flavor.prototype.setRxtxFactor = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional int32 swap = 7;
 * @return {number}
 */
proto.poolmanager.Flavor.prototype.getSwap = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.poolmanager.Flavor} returns this
 */
proto.poolmanager.Flavor.prototype.setSwap = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 ephemeral = 8;
 * @return {number}
 */
proto.poolmanager.Flavor.prototype.getEphemeral = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.poolmanager.Flavor} returns this
 */
proto.poolmanager.Flavor.prototype.setEphemeral = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional bool is_public = 9;
 * @return {boolean}
 */
proto.poolmanager.Flavor.prototype.getIsPublic = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.poolmanager.Flavor} returns this
 */
proto.poolmanager.Flavor.prototype.setIsPublic = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional string description = 10;
 * @return {string}
 */
proto.poolmanager.Flavor.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Flavor} returns this
 */
proto.poolmanager.Flavor.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string extra_specs = 11;
 * @return {string}
 */
proto.poolmanager.Flavor.prototype.getExtraSpecs = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Flavor} returns this
 */
proto.poolmanager.Flavor.prototype.setExtraSpecs = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.poolmanager.Network.prototype.toObject = function(opt_includeInstance) {
  return proto.poolmanager.Network.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.poolmanager.Network} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.poolmanager.Network.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, ""),
name: jspb.Message.getFieldWithDefault(msg, 2, ""),
description: jspb.Message.getFieldWithDefault(msg, 3, ""),
adminStateUp: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
status: jspb.Message.getFieldWithDefault(msg, 5, ""),
tenantId: jspb.Message.getFieldWithDefault(msg, 6, ""),
projectId: jspb.Message.getFieldWithDefault(msg, 7, ""),
shared: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
revisionNumber: jspb.Message.getFieldWithDefault(msg, 9, 0),
subnets: jspb.Message.getFieldWithDefault(msg, 10, ""),
availabilityZoneHints: jspb.Message.getFieldWithDefault(msg, 11, ""),
tags: jspb.Message.getFieldWithDefault(msg, 12, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.poolmanager.Network}
 */
proto.poolmanager.Network.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.poolmanager.Network;
  return proto.poolmanager.Network.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.poolmanager.Network} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.poolmanager.Network}
 */
proto.poolmanager.Network.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAdminStateUp(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setTenantId(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setProjectId(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShared(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRevisionNumber(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubnets(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setAvailabilityZoneHints(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setTags(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.poolmanager.Network.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.poolmanager.Network.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.poolmanager.Network} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.poolmanager.Network.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAdminStateUp();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTenantId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getProjectId();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getShared();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getRevisionNumber();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getSubnets();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getAvailabilityZoneHints();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getTags();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.poolmanager.Network.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Network} returns this
 */
proto.poolmanager.Network.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.poolmanager.Network.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Network} returns this
 */
proto.poolmanager.Network.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.poolmanager.Network.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Network} returns this
 */
proto.poolmanager.Network.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bool admin_state_up = 4;
 * @return {boolean}
 */
proto.poolmanager.Network.prototype.getAdminStateUp = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.poolmanager.Network} returns this
 */
proto.poolmanager.Network.prototype.setAdminStateUp = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional string status = 5;
 * @return {string}
 */
proto.poolmanager.Network.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Network} returns this
 */
proto.poolmanager.Network.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string tenant_id = 6;
 * @return {string}
 */
proto.poolmanager.Network.prototype.getTenantId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Network} returns this
 */
proto.poolmanager.Network.prototype.setTenantId = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string project_id = 7;
 * @return {string}
 */
proto.poolmanager.Network.prototype.getProjectId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Network} returns this
 */
proto.poolmanager.Network.prototype.setProjectId = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional bool shared = 8;
 * @return {boolean}
 */
proto.poolmanager.Network.prototype.getShared = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.poolmanager.Network} returns this
 */
proto.poolmanager.Network.prototype.setShared = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional int32 revision_number = 9;
 * @return {number}
 */
proto.poolmanager.Network.prototype.getRevisionNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.poolmanager.Network} returns this
 */
proto.poolmanager.Network.prototype.setRevisionNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional string subnets = 10;
 * @return {string}
 */
proto.poolmanager.Network.prototype.getSubnets = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Network} returns this
 */
proto.poolmanager.Network.prototype.setSubnets = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string availability_zone_hints = 11;
 * @return {string}
 */
proto.poolmanager.Network.prototype.getAvailabilityZoneHints = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Network} returns this
 */
proto.poolmanager.Network.prototype.setAvailabilityZoneHints = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string tags = 12;
 * @return {string}
 */
proto.poolmanager.Network.prototype.getTags = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.poolmanager.Network} returns this
 */
proto.poolmanager.Network.prototype.setTags = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * @enum {number}
 */
proto.poolmanager.Status = {
  STATUS_UNKNOWN: 0,
  CREATE: 1,
  UPDATE: 2,
  DELETE: 3
};

/**
 * @enum {number}
 */
proto.poolmanager.Type = {
  TYPE_UNKNOWN: 0,
  SERVERPOOL: 1,
  SERVER: 2,
  CONFIG: 3
};

goog.object.extend(exports, proto.poolmanager);
