/**
 * @fileoverview gRPC-Web generated client stub for poolmanager
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.0
// source: poolmanager.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"
import * as poolmanager_pb from './poolmanager_pb'; // proto import: "poolmanager.proto"


export class PoolManagerClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSendRessources = new grpcWeb.MethodDescriptor(
    '/poolmanager.PoolManager/SendRessources',
    grpcWeb.MethodType.UNARY,
    poolmanager_pb.RessourceRequest,
    google_protobuf_empty_pb.Empty,
    (request: poolmanager_pb.RessourceRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  sendRessources(
    request: poolmanager_pb.RessourceRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  sendRessources(
    request: poolmanager_pb.RessourceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  sendRessources(
    request: poolmanager_pb.RessourceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/poolmanager.PoolManager/SendRessources',
        request,
        metadata || {},
        this.methodDescriptorSendRessources,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/poolmanager.PoolManager/SendRessources',
    request,
    metadata || {},
    this.methodDescriptorSendRessources);
  }

  methodDescriptorGetStreamRessources = new grpcWeb.MethodDescriptor(
    '/poolmanager.PoolManager/GetStreamRessources',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    poolmanager_pb.StreamRessourceResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    poolmanager_pb.StreamRessourceResponse.deserializeBinary
  );

  getStreamRessources(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<poolmanager_pb.StreamRessourceResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/poolmanager.PoolManager/GetStreamRessources',
      request,
      metadata || {},
      this.methodDescriptorGetStreamRessources);
  }

  methodDescriptorGetStreamRessourcesUser = new grpcWeb.MethodDescriptor(
    '/poolmanager.PoolManager/GetStreamRessourcesUser',
    grpcWeb.MethodType.SERVER_STREAMING,
    poolmanager_pb.UserRequest,
    poolmanager_pb.StreamRessourceResponse,
    (request: poolmanager_pb.UserRequest) => {
      return request.serializeBinary();
    },
    poolmanager_pb.StreamRessourceResponse.deserializeBinary
  );

  getStreamRessourcesUser(
    request: poolmanager_pb.UserRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<poolmanager_pb.StreamRessourceResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/poolmanager.PoolManager/GetStreamRessourcesUser',
      request,
      metadata || {},
      this.methodDescriptorGetStreamRessourcesUser);
  }

  methodDescriptorGetAllImages = new grpcWeb.MethodDescriptor(
    '/poolmanager.PoolManager/GetAllImages',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    poolmanager_pb.Image,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    poolmanager_pb.Image.deserializeBinary
  );

  getAllImages(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<poolmanager_pb.Image> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/poolmanager.PoolManager/GetAllImages',
      request,
      metadata || {},
      this.methodDescriptorGetAllImages);
  }

  methodDescriptorGetAllFlavors = new grpcWeb.MethodDescriptor(
    '/poolmanager.PoolManager/GetAllFlavors',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    poolmanager_pb.Flavor,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    poolmanager_pb.Flavor.deserializeBinary
  );

  getAllFlavors(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<poolmanager_pb.Flavor> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/poolmanager.PoolManager/GetAllFlavors',
      request,
      metadata || {},
      this.methodDescriptorGetAllFlavors);
  }

  methodDescriptorGetAllNetworks = new grpcWeb.MethodDescriptor(
    '/poolmanager.PoolManager/GetAllNetworks',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    poolmanager_pb.Network,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    poolmanager_pb.Network.deserializeBinary
  );

  getAllNetworks(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<poolmanager_pb.Network> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/poolmanager.PoolManager/GetAllNetworks',
      request,
      metadata || {},
      this.methodDescriptorGetAllNetworks);
  }

}

